### PR TITLE
Add documentation to plugin, and minor refactor 

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
:)

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
(I can take care to update the example to express4 if you're interested)

**Comment by nherment** [comment]
@AdrieanKhisbe, needs conflict resolution. Would you have time to look into it ?

**Comment by AdrieanKhisbe** [comment]
Yep Yep, will do in the coming days ;)

**Comment by mihaidma** [comment]
@AdrieanKhisbe will you do also linting and stuff? If so I can leave this assigned to you.

**Comment by AdrieanKhisbe** [comment]
can take care of it, as long as this can wait for sunday :)

**Comment by mihaidma** [comment]
ok, sounds good

**Comment by AdrieanKhisbe** [comment]
> `Seneca Microservices Framework member`
> what is this new badge? ^^

**Comment by AdrieanKhisbe** [comment]
(oh, I have too)

**Comment by AdrieanKhisbe** [comment]
@mihaidma Here it is! :smiley:

**Comment by mihaidma** [comment]
Looks, good. Thank you :)

**Comment by AdrieanKhisbe** [comment]
(:

**Pull request merged**
